### ISSUE TITLE
Use SSM public data to grab SDK endpoints

### ISSUE THREAD

**Issue by cjoftheweb** [soto-project/soto#143]
Instead of using the endpoint JSON files included with Go, there is [an API](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html) for accessing endpoint information and service availability based on region. This information is always up to date with new regions, so it’s much less likely to deviate from reality.

**Comment by adam-fowler** [comment]
We could add an updateEndpoints() to the client, that uses the info from SSM to update ```serviceEndpoints```. If this isn't run then we default to the endpoint JSON from the Go repository. Most services endpoints are static so shouldn't need to keep asking for the service endpoints. 

What's your thoughts @jonnymacs @Yasumoto ?

**Comment by Yasumoto** [comment]
That'd be using [this, right](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters.html#parameter-store-public-parameters-global-infrastructure)? Since these don't change ~too much I think it's solid to keep the default hardcoded (like the golang SDK) but make this an option. Maybe we call it `refreshEndpoints()` (but `updateEndpoints()` is a-ok 👌 too) or something so it replaces them with current options? 🤔 

@cjoftheweb do you have an example of when/how this is useful just to help me see the workflow?

**Comment by cjoftheweb** [comment]
An example of when the endpoints do change is upon release of every new region. The more often AWS releases regions, the more often this happens. At least for now, this probably isn’t the highest priority, but it decouples the codebase from having to change whenever AWS regions change.

**Comment by adam-fowler** [comment]
Given we now have support for arbitrary regions via `Region.other("my-region")` we have decoupled the codebase from AWS changes to some degree. I'm going to close this for now.
