### ISSUE TITLE
PutObjectRequest API  how to get progress

### ISSUE THREAD

**Issue by chenanghui** [soto-project/soto#707]
PutObjectRequest API  how to get progress

**Comment by adam-fowler** [comment]
The PutObject API accepts an AsyncSequence of ByteBuffers. You could break up the buffer you are sending into an AsyncSequence of buffers and then use `map` to track the buffers the HTTPClient is reading from this sequence. 

Alternatively instead of map you could use something like this https://github.com/soto-project/soto/blob/main/Sources/Soto/Extensions/S3/ReportSizeByteBufferSequence.swift
